apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vbm-data-pvc
  namespace: vbm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: vbmd
